name: helm-upgrade
run-name: ${{github.actor}} - ${{github.ref_name}}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      helm-path:
        type: string
        default: ./todoapp/values.yml
      helm-release:
        type: string
        default: todoapp

jobs:
  deploy-helm:
    name: ${{inputs.environment}}
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Download Helm artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Download Helm artifact (tgz)
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Set Up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      # - name: Azure login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{}}
